package com.sstinternaltools.sstinternal_tools.mess.mapper.interfaces;

import com.sstinternaltools.sstinternal_tools.mess.dto.vendorPlanSelectionHistoryDtos.VendorPlanSelectionHistorySummaryDto;

public interface VendorPlanSelectionHistoryDtoMapper <VendorPlanSelectionHistory> {
    VendorPlanSelectionHistorySummaryDto toSummaryDto(VendorPlanSelectionHistory vendorPlanSelectionHistory);
}